bool checkWhite(int board[8][8], int x, int y);
bool checkBlack(int board[8][8], int x, int y);
bool checkMateWhite(int board[8][8], int x, int y);
bool checkMateBlack(int board[8][8], int x, int y);
bool selectionWhiteCheck(int board[8][8], int x, int y, int enemyX, int enemyY);
bool selectionBlackCheck(int board[9][8], int x, int y, int enemyX, int enemyY);
bool checkBlackLateral(int board[8][8], int x, int y);
bool checkBlackDiagonal(int board[8][8] , int x, int y);
bool checkEnemyWhiteHorse(int board[8][8], int x, int y);
bool checkBlackSurrounding(int board[8][8] , int x, int y);
